/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Control.ControleCaixa;
import Model.ModeloCaixa;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import Util.ConectaBanco;

/**
 *
 * @author Maycon Silva
 */
public class FrmCaixa extends javax.swing.JInternalFrame {
    
    ModeloCaixa mod = new ModeloCaixa();
    ControleCaixa control = new ControleCaixa();
    ConectaBanco conecta = new ConectaBanco();
        
    private int flag;

    /**
     * Creates new form FrmColecao
     */
    public FrmCaixa() {
        initComponents();
        
        this.setLocation(450,100);
        
        //Método não encerrar a tela sem fechar
        setClosable(true);
        
        //Inicio do código fonte inativa todos menus
        jMenuNovo.setEnabled(true);
        jMenuSalvar.setEnabled(false);
        jMenuEditar.setEnabled(false);
        jMenuExluir.setEnabled(false);
        jMenuCancelar.setEnabled(false);
        
        jTextFieldCodigo.setEnabled(true);
        jTextFieldNumeroCaixa.setEnabled(false); 
        jTextFieldCodEtiqueta.setEnabled(false);  
        jTextFieldCor.setEnabled(false);          
                
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextFieldCodigo = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldNumeroCaixa = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jButtonBuscar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldCodEtiqueta = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldCor = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuNovo = new javax.swing.JMenu();
        jMenuSalvar = new javax.swing.JMenu();
        jMenuEditar = new javax.swing.JMenu();
        jMenuExluir = new javax.swing.JMenu();
        jMenuCancelar = new javax.swing.JMenu();

        setIconifiable(true);
        setTitle("CADASTRO DE CAIXA");

        jLabel1.setText("Código:");

        jLabel2.setText("Número:");

        jButtonBuscar.setText("PESQUISAR");
        jButtonBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscarActionPerformed(evt);
            }
        });

        jLabel3.setText("Cód. Etiqueta");

        jLabel4.setText("Cor:");

        jMenuNovo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/folder-plus.png"))); // NOI18N
        jMenuNovo.setText("NOVO");
        jMenuNovo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuNovoMouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenuNovo);

        jMenuSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/content-save.png"))); // NOI18N
        jMenuSalvar.setText("SALVAR");
        jMenuSalvar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuSalvarMouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenuSalvar);

        jMenuEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/folder-edit.png"))); // NOI18N
        jMenuEditar.setText("EDITAR");
        jMenuEditar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuEditarMouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenuEditar);

        jMenuExluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/trash-can.png"))); // NOI18N
        jMenuExluir.setText("EXCLUIR");
        jMenuExluir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuExluirMouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenuExluir);

        jMenuCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/eraser.png"))); // NOI18N
        jMenuCancelar.setText("CANCELAR");
        jMenuCancelar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuCancelarMouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenuCancelar);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldCor, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTextFieldCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonBuscar))
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jTextFieldCodEtiqueta, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jTextFieldNumeroCaixa, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE))
                    .addComponent(jLabel4))
                .addContainerGap(229, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonBuscar))
                .addGap(2, 2, 2)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldNumeroCaixa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldCodEtiqueta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldCor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(78, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuSalvarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuSalvarMouseClicked
        if(jMenuSalvar.isEnabled()){
            //IF SALVAR
            if(flag == 1){
                mod.setNumeroCaixa(Integer.parseInt(jTextFieldNumeroCaixa.getText()));
                mod.setIdentificacaoEtiquetaCaixa(jTextFieldCodEtiqueta.getText());
                mod.setCorCaixa(jTextFieldCor.getText());
                control.SalvarCaixa(mod);
                
                buscarUltimaInsercao();
                
                //Método ativa os menus
                jMenuNovo.setEnabled(true);
                jMenuSalvar.setEnabled(false);
                jMenuEditar.setEnabled(true);
                jMenuExluir.setEnabled(true);
                jMenuCancelar.setEnabled(false);
                
                jTextFieldCodigo.setEnabled(true);
                jTextFieldNumeroCaixa.setEnabled(false);
                jTextFieldCodEtiqueta.setEnabled(false);  
                jTextFieldCor.setEnabled(false);          
            }
            //ELSE EDITAR
            else{
                mod.setNumeroCaixa(Integer.parseInt(jTextFieldNumeroCaixa.getText()));
                mod.setIdentificacaoEtiquetaCaixa(jTextFieldCodEtiqueta.getText());
                mod.setCorCaixa(jTextFieldCor.getText());
                mod.setIdCaixa(Integer.parseInt(jTextFieldCodigo.getText()));
                control.EditarCaixa(mod);
                
                //buscarUltimaInsercao();
                
                //Método ativa os menus
                jMenuNovo.setEnabled(true);
                jMenuSalvar.setEnabled(false);
                jMenuEditar.setEnabled(true);
                jMenuExluir.setEnabled(true);
                jMenuCancelar.setEnabled(false);
                
                jTextFieldCodigo.setEnabled(true);
                jTextFieldNumeroCaixa.setEnabled(false); 
                jTextFieldCodEtiqueta.setEnabled(false);  
                jTextFieldCor.setEnabled(false);          
            }            
        }                
        
    }//GEN-LAST:event_jMenuSalvarMouseClicked

    private void jMenuNovoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuNovoMouseClicked
        if(jMenuNovo.isEnabled()){
            flag = 1;
            
            //Método ativa os menus
            jMenuNovo.setEnabled(false);
            jMenuSalvar.setEnabled(true);
            jMenuEditar.setEnabled(false);
            jMenuExluir.setEnabled(false);
            jMenuCancelar.setEnabled(true);
            jButtonBuscar.setEnabled(false);
            
            jTextFieldCodigo.setEnabled(false);
            jTextFieldNumeroCaixa.setEnabled(true);
            jTextFieldCodEtiqueta.setEnabled(true);  
            jTextFieldCor.setEnabled(true);          
            
            jTextFieldCodigo.setText("");
            jTextFieldNumeroCaixa.setText(""); 
            jTextFieldCodEtiqueta.setText("");
            jTextFieldCor.setText("");
        }        
    }//GEN-LAST:event_jMenuNovoMouseClicked

    private void jMenuEditarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuEditarMouseClicked
        if(jMenuEditar.isEnabled()){
            flag = 2;
            
            //Método ativa os menus
            jMenuNovo.setEnabled(false);
            jMenuSalvar.setEnabled(true);
            jMenuEditar.setEnabled(false);
            jMenuExluir.setEnabled(false);
            jMenuCancelar.setEnabled(true);
            
            jTextFieldCodigo.setEnabled(false);
            jTextFieldNumeroCaixa.setEnabled(true);
            jTextFieldCodEtiqueta.setEnabled(true);  
            jTextFieldCor.setEnabled(true);          
        }
    }//GEN-LAST:event_jMenuEditarMouseClicked

    private void jMenuCancelarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuCancelarMouseClicked
        if (jMenuCancelar.isEnabled()) {
            //Método ativa os menus
            jMenuNovo.setEnabled(true);
            jMenuSalvar.setEnabled(false);
            jMenuEditar.setEnabled(false);
            jMenuExluir.setEnabled(false);
            jMenuCancelar.setEnabled(false);
            jButtonBuscar.setEnabled(true);

            jTextFieldCodigo.setEnabled(true);
            jTextFieldNumeroCaixa.setEnabled(false);
            jTextFieldCodEtiqueta.setEnabled(false);  
            jTextFieldCor.setEnabled(false);          
            
            jTextFieldCodigo.setText("");
            jTextFieldNumeroCaixa.setText("");
            jTextFieldCodEtiqueta.setText("");
            jTextFieldCor.setText("");
        }           
    }//GEN-LAST:event_jMenuCancelarMouseClicked

    private void jMenuExluirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuExluirMouseClicked
        if(jMenuExluir.isEnabled()){
            if(!jTextFieldCodigo.equals("")){
                mod.setIdCaixa(Integer.parseInt(jTextFieldCodigo.getText()));
                control.ExcluirCaixa(mod);
                                
                //Método ativa os menus
                jMenuNovo.setEnabled(true);
                jMenuSalvar.setEnabled(false);
                jMenuEditar.setEnabled(false);
                jMenuExluir.setEnabled(false);
                jMenuCancelar.setEnabled(false);
                
                jTextFieldCodigo.setEnabled(true);
                jTextFieldNumeroCaixa.setEnabled(false);
                jTextFieldCodEtiqueta.setEnabled(false);  
                jTextFieldCor.setEnabled(false);          
                
                jTextFieldCodigo.setText("");
                jTextFieldNumeroCaixa.setText("");
                jTextFieldCodEtiqueta.setText("");
                jTextFieldCor.setText("");
            }
        }
                
    }//GEN-LAST:event_jMenuExluirMouseClicked

    private void jButtonBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscarActionPerformed
        if(jTextFieldCodigo.getText().equals("")){
            FrmConsultaCaixa frmContulta = new FrmConsultaCaixa(null, true);
            frmContulta.setVisible(true);          
            
            String idColecao = frmContulta.getIdCodigo();
            String numero = frmContulta.getNumero();
            String codEtiqueta = frmContulta.getCodEtiqueta();
            String cor = frmContulta.getCor();
            
            jTextFieldCodigo.setText(idColecao);
            jTextFieldNumeroCaixa.setText(numero);
            jTextFieldCodEtiqueta.setText(codEtiqueta);  
            jTextFieldCor.setText(cor);
            
            jMenuNovo.setEnabled(true);
            jMenuSalvar.setEnabled(false);
            jMenuEditar.setEnabled(true);
            jMenuExluir.setEnabled(true);
            jMenuCancelar.setEnabled(true);
            jButtonBuscar.setEnabled(false);
        }else{
            
            control.CarregarCaixa(Integer.parseInt(jTextFieldCodigo.getText().toString()));          
            int numero = control.getNum(); 
            String idenf = control.getIdentif();
            String cor = control.getCor();
            jTextFieldNumeroCaixa.setText(String.valueOf(numero));
            jTextFieldCodEtiqueta.setText(idenf);  
            jTextFieldCor.setText(cor);  
            
            jMenuNovo.setEnabled(true);
            jMenuSalvar.setEnabled(false);
            jMenuEditar.setEnabled(true);
            jMenuExluir.setEnabled(true);
            jMenuCancelar.setEnabled(true);
            jButtonBuscar.setEnabled(false);
            
        }
    }//GEN-LAST:event_jButtonBuscarActionPerformed

    public void buscarUltimaInsercao(){
        String nomeAmigo = jTextFieldNumeroCaixa.getText().toString();
        //conecta.desconecta();
        conecta.conexao(); 
        conecta.executaSQL("SELECT max(id_tblAmigo) as numeroPego FROM tblAmigo where nome_tblAmigo = '"+nomeAmigo+"'");
        try { 
            while(conecta.rs.next()){
                String idPego = conecta.rs.getString("numeroPego");
                System.out.println(idPego);
                jTextFieldCodigo.setText(idPego);
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Erro ao buscar id da coleção!\nERRO:"+ex);
        }
    }
    
    
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBuscar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuCancelar;
    private javax.swing.JMenu jMenuEditar;
    private javax.swing.JMenu jMenuExluir;
    private javax.swing.JMenu jMenuNovo;
    private javax.swing.JMenu jMenuSalvar;
    private javax.swing.JTextField jTextFieldCodEtiqueta;
    private javax.swing.JTextField jTextFieldCodigo;
    private javax.swing.JTextField jTextFieldCor;
    private javax.swing.JTextField jTextFieldNumeroCaixa;
    // End of variables declaration//GEN-END:variables
}
