/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Model.ModeloTabela;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import Util.ConectaBanco;

/**
 *
 * @author Maycon Silva
 */
public class FrmEmprestados extends javax.swing.JInternalFrame {
    
    ConectaBanco conecta = new ConectaBanco();

    /**
     * Creates new form FrmEmprestados
     */
    public FrmEmprestados() {
        initComponents();
        
        this.setLocation(340,35);
        this.setSize(700,544);          
        setClosable(true);     
        
        preencherTabelaLivrosEmprestados("select id_tblEmprestimo, dataEmprestimo_tblEmprestimo, dataDevolucao_tblEmprestimo, nomeAmigo_tblEmprestimo, livro_tblEmprestimo,ano_tblRevistas,numeroEdicao_tblRevistas from tblEmprestimo inner join tblRevistas on tblRevistas.colecao_tblRevistas = tblEmprestimo.livro_tblEmprestimo"); 
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTableLivrosEmprestados = new javax.swing.JTable();

        setIconifiable(true);
        setTitle("LIVROS EMPRESTADOS");
        setToolTipText("");

        jTableLivrosEmprestados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jTableLivrosEmprestados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableLivrosEmprestadosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableLivrosEmprestados);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 664, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 452, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTableLivrosEmprestadosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableLivrosEmprestadosMouseClicked
        
    }//GEN-LAST:event_jTableLivrosEmprestadosMouseClicked
    
    
    public void preencherTabelaLivrosEmprestados(String sql){
        ArrayList dados = new ArrayList();
        
        String[] Colunas = new String[]{"ID","NOME","RETIRADA","DEVOLUÇÃO","LIVRO","ANO LIVRO","Nº EDIÇÃO"};
        conecta.conexao();
        conecta.executaSQL(sql);
        try{
            conecta.rs.next();
            do{
                dados.add(new Object[]{ conecta.rs.getString("id_tblEmprestimo") ,conecta.rs.getString("nomeAmigo_tblEmprestimo"),conecta.rs.getString("dataEmprestimo_tblEmprestimo"),conecta.rs.getString("dataDevolucao_tblEmprestimo"),conecta.rs.getString("livro_tblEmprestimo"),conecta.rs.getString("ano_tblRevistas"),conecta.rs.getString("numeroEdicao_tblRevistas")});
                
            }while (conecta.rs.next());
        }catch (SQLException ex){
                JOptionPane.showMessageDialog(null, "Livros emprestados não encontrado");
        }
        
        ModeloTabela modelo = new ModeloTabela(dados, Colunas);
        jTableLivrosEmprestados.setModel(modelo);
        jTableLivrosEmprestados.getColumnModel().getColumn(0).setPreferredWidth(40);
        jTableLivrosEmprestados.getColumnModel().getColumn(0).setResizable(false);
        jTableLivrosEmprestados.getColumnModel().getColumn(1).setPreferredWidth(250);
        jTableLivrosEmprestados.getColumnModel().getColumn(1).setResizable(false);
        jTableLivrosEmprestados.getColumnModel().getColumn(2).setPreferredWidth(120);
        jTableLivrosEmprestados.getColumnModel().getColumn(2).setResizable(false);
        jTableLivrosEmprestados.getColumnModel().getColumn(3).setPreferredWidth(120);
        jTableLivrosEmprestados.getColumnModel().getColumn(3).setResizable(false);
        jTableLivrosEmprestados.getColumnModel().getColumn(4).setPreferredWidth(300);
        jTableLivrosEmprestados.getColumnModel().getColumn(4).setResizable(false);
        jTableLivrosEmprestados.getColumnModel().getColumn(5).setPreferredWidth(100);
        jTableLivrosEmprestados.getColumnModel().getColumn(5).setResizable(false);
        jTableLivrosEmprestados.getColumnModel().getColumn(6).setPreferredWidth(100);
        jTableLivrosEmprestados.getColumnModel().getColumn(6).setResizable(false);
        jTableLivrosEmprestados.getTableHeader().setReorderingAllowed(false);
        jTableLivrosEmprestados.setAutoResizeMode(jTableLivrosEmprestados.AUTO_RESIZE_OFF);
        jTableLivrosEmprestados.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
    }
   

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableLivrosEmprestados;
    // End of variables declaration//GEN-END:variables
}
