/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Control.ControleRevista;
import Model.ModeloRevistas;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import Util.ConectaBanco;

/**
 *
 * @author Maycon Silva
 */
public class FrmRevista extends javax.swing.JInternalFrame {
    
    ModeloRevistas mod = new ModeloRevistas();
    ControleRevista control = new ControleRevista();
    ConectaBanco conecta = new ConectaBanco();
        
    private int flag;

    /**
     * Creates new form FrmColecao
     */
    public FrmRevista() {
        initComponents();
        
        this.setLocation(450,100);
        
        //Método não encerrar a tela sem fechar
        setClosable(true);
        
        //Inicio do código fonte inativa todos menus
        jMenuNovo.setEnabled(true);
        jMenuSalvar.setEnabled(false);
        jMenuEditar.setEnabled(false);
        jMenuExluir.setEnabled(false);
        jMenuCancelar.setEnabled(false);
        jButtonPesquisarColecao.setEnabled(false);
        
        jTextFieldCodigo.setEnabled(true);
        jTextFieldNumeroEdicao.setEnabled(false); 
        jTextFieldAno.setEnabled(false);  
        jTextFieldCaixa.setEnabled(false);
        jTextFieldColecao.setEnabled(false);
        
        preencherComboboxCaixa();
                
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextFieldCodigo = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldNumeroEdicao = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jButtonBuscar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldAno = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldCaixa = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldColecao = new javax.swing.JTextField();
        jButtonPesquisarColecao = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuNovo = new javax.swing.JMenu();
        jMenuSalvar = new javax.swing.JMenu();
        jMenuEditar = new javax.swing.JMenu();
        jMenuExluir = new javax.swing.JMenu();
        jMenuCancelar = new javax.swing.JMenu();

        setIconifiable(true);
        setTitle("CADASTRO DE REVISTAS");

        jLabel1.setText("Código:");

        jLabel2.setText("Nº Edição");

        jButtonBuscar.setText("PESQUISAR");
        jButtonBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscarActionPerformed(evt);
            }
        });

        jLabel3.setText("Ano:");

        jLabel4.setText("Caixa:");

        jTextFieldCaixa.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel5.setText("Coleção:");

        jButtonPesquisarColecao.setText("PESQUISAR");
        jButtonPesquisarColecao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPesquisarColecaoActionPerformed(evt);
            }
        });

        jMenuNovo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/folder-plus.png"))); // NOI18N
        jMenuNovo.setText("NOVO");
        jMenuNovo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuNovoMouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenuNovo);

        jMenuSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/content-save.png"))); // NOI18N
        jMenuSalvar.setText("SALVAR");
        jMenuSalvar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuSalvarMouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenuSalvar);

        jMenuEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/folder-edit.png"))); // NOI18N
        jMenuEditar.setText("EDITAR");
        jMenuEditar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuEditarMouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenuEditar);

        jMenuExluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/trash-can.png"))); // NOI18N
        jMenuExluir.setText("EXCLUIR");
        jMenuExluir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuExluirMouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenuExluir);

        jMenuCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/eraser.png"))); // NOI18N
        jMenuCancelar.setText("CANCELAR");
        jMenuCancelar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuCancelarMouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenuCancelar);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTextFieldCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonBuscar))
                    .addComponent(jLabel5)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jTextFieldNumeroEdicao)
                    .addComponent(jTextFieldAno)
                    .addComponent(jTextFieldCaixa, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2)
                    .addComponent(jTextFieldColecao))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonPesquisarColecao)
                .addContainerGap(134, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonBuscar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldColecao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonPesquisarColecao))
                .addGap(9, 9, 9)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldNumeroEdicao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldAno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldCaixa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuSalvarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuSalvarMouseClicked
        if(jMenuSalvar.isEnabled()){
            //IF SALVAR
            if(flag == 1){
                System.out.println("chamou aqui");
                mod.setNumeroEdicao(Integer.parseInt(jTextFieldNumeroEdicao.getText()));
                mod.setAno(Integer.parseInt(jTextFieldAno.getText()));
                mod.setCaixa((String) jTextFieldCaixa.getSelectedItem());
                mod.setColecao(jTextFieldColecao.getText());
                control.SalvarRevista(mod);
                
                buscarUltimaInsercao();
                
                //Método ativa os menus
                jMenuNovo.setEnabled(true);
                jMenuSalvar.setEnabled(false);
                jMenuEditar.setEnabled(true);
                jMenuExluir.setEnabled(true);
                jMenuCancelar.setEnabled(false);
                jButtonPesquisarColecao.setEnabled(false);
                
                jTextFieldCodigo.setEnabled(true);
                jTextFieldNumeroEdicao.setEnabled(false);
                jTextFieldAno.setEnabled(false);  
                jTextFieldCaixa.setEnabled(false);          
            }
            //ELSE EDITAR
            else{
                mod.setNumeroEdicao(Integer.parseInt(jTextFieldNumeroEdicao.getText()));
                mod.setAno(Integer.parseInt(jTextFieldAno.getText()));
                mod.setCaixa((String) jTextFieldCaixa.getSelectedItem());
                mod.setColecao(jTextFieldColecao.getText());                
                mod.setIdRevista(Integer.parseInt(jTextFieldCodigo.getText()));
                control.EditarRevista(mod);
                
                //buscarUltimaInsercao();
                
                //Método ativa os menus
                jMenuNovo.setEnabled(true);
                jMenuSalvar.setEnabled(false);
                jMenuEditar.setEnabled(true);
                jMenuExluir.setEnabled(true);
                jMenuCancelar.setEnabled(false);
                jButtonPesquisarColecao.setEnabled(false);
                
                jTextFieldCodigo.setEnabled(true);
                jTextFieldNumeroEdicao.setEnabled(false); 
                jTextFieldAno.setEnabled(false);  
                jTextFieldCaixa.setEnabled(false);          
            }            
        }                
        
    }//GEN-LAST:event_jMenuSalvarMouseClicked

    private void jMenuNovoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuNovoMouseClicked
        if(jMenuNovo.isEnabled()){
            flag = 1;
            
            //Método ativa os menus
            jMenuNovo.setEnabled(false);
            jMenuSalvar.setEnabled(true);
            jMenuEditar.setEnabled(false);
            jMenuExluir.setEnabled(false);
            jMenuCancelar.setEnabled(true);
            jButtonBuscar.setEnabled(false);
            jButtonPesquisarColecao.setEnabled(true);
            
            jTextFieldCodigo.setEnabled(false);
            jTextFieldNumeroEdicao.setEnabled(true);
            jTextFieldAno.setEnabled(true);  
            jTextFieldCaixa.setEnabled(true); 
            jTextFieldColecao.setEnabled(false);
            
            jTextFieldCodigo.setText("");
            jTextFieldNumeroEdicao.setText(""); 
            jTextFieldAno.setText("");
            jTextFieldColecao.setText("");
        }        
    }//GEN-LAST:event_jMenuNovoMouseClicked

    private void jMenuEditarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuEditarMouseClicked
        if(jMenuEditar.isEnabled()){
            flag = 2;
            
            //Método ativa os menus
            jMenuNovo.setEnabled(false);
            jMenuSalvar.setEnabled(true);
            jMenuEditar.setEnabled(false);
            jMenuExluir.setEnabled(false);
            jMenuCancelar.setEnabled(true);
            jButtonPesquisarColecao.setEnabled(false);
            
            jTextFieldCodigo.setEnabled(false);
            jTextFieldNumeroEdicao.setEnabled(true);
            jTextFieldAno.setEnabled(true);  
            jTextFieldCaixa.setEnabled(true);
            jTextFieldColecao.setEnabled(false);
        }
    }//GEN-LAST:event_jMenuEditarMouseClicked

    private void jMenuCancelarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuCancelarMouseClicked
        if (jMenuCancelar.isEnabled()) {
            //Método ativa os menus
            jMenuNovo.setEnabled(true);
            jMenuSalvar.setEnabled(false);
            jMenuEditar.setEnabled(false);
            jMenuExluir.setEnabled(false);
            jMenuCancelar.setEnabled(false);
            jButtonBuscar.setEnabled(true);
            jButtonPesquisarColecao.setEnabled(false);

            jTextFieldCodigo.setEnabled(true);
            jTextFieldNumeroEdicao.setEnabled(false);
            jTextFieldAno.setEnabled(false);  
            jTextFieldCaixa.setEnabled(false); 
            jTextFieldColecao.setEnabled(false);
            
            jTextFieldCodigo.setText("");
            jTextFieldNumeroEdicao.setText("");
            jTextFieldAno.setText("");
            jTextFieldColecao.setText("");
        }           
    }//GEN-LAST:event_jMenuCancelarMouseClicked

    private void jMenuExluirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuExluirMouseClicked
        if(jMenuExluir.isEnabled()){
            if(!jTextFieldCodigo.equals("")){
                mod.setIdRevista(Integer.parseInt(jTextFieldCodigo.getText()));
                control.ExcluirRevista(mod);
                                
                //Método ativa os menus
                jMenuNovo.setEnabled(true);
                jMenuSalvar.setEnabled(false);
                jMenuEditar.setEnabled(false);
                jMenuExluir.setEnabled(false);
                jMenuCancelar.setEnabled(false);
                jButtonPesquisarColecao.setEnabled(false);
                
                jTextFieldCodigo.setEnabled(true);
                jTextFieldNumeroEdicao.setEnabled(false);
                jTextFieldAno.setEnabled(false);  
                jTextFieldCaixa.setEnabled(false); 
                jTextFieldColecao.setEnabled(false);
                
                jTextFieldCodigo.setText("");
                jTextFieldNumeroEdicao.setText("");
                jTextFieldAno.setText("");
                jTextFieldColecao.setText("");
            }
        }
                
    }//GEN-LAST:event_jMenuExluirMouseClicked

    private void jButtonBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscarActionPerformed
        if(jTextFieldCodigo.getText().equals("")){
            FrmConsultaRevista frmContulta = new FrmConsultaRevista(null, true);
            frmContulta.setVisible(true);          
            
            String idRevista = frmContulta.getIdCodigo();
            String numEdicao = frmContulta.getNumeroEdicao();
            String ano = frmContulta.getAnoRevista();
            String caixa = frmContulta.getCaixaRevista();
            String colecao = frmContulta.getColecao();
            
            jTextFieldCodigo.setText(idRevista);
            jTextFieldNumeroEdicao.setText(numEdicao);
            jTextFieldAno.setText(ano);  
            jTextFieldCaixa.setSelectedItem(caixa);
            jTextFieldColecao.setText(colecao);
            
            jMenuNovo.setEnabled(true);
            jMenuSalvar.setEnabled(false);
            jMenuEditar.setEnabled(true);
            jMenuExluir.setEnabled(true);
            jMenuCancelar.setEnabled(true);
            jButtonBuscar.setEnabled(false);
        }else{
            
            control.CarregarRevistas(Integer.parseInt(jTextFieldCodigo.getText().toString()));          
            int numEdicao = control.getNumeroRev(); 
            int anoEdicao = control.getAnoRev();
            String caixaRevi = control.getCaixaRev();
            String colecao = control.getColecao();
            jTextFieldNumeroEdicao.setText(String.valueOf(numEdicao));
            jTextFieldAno.setText(String.valueOf(anoEdicao));  
            jTextFieldCaixa.setSelectedItem(String.valueOf(caixaRevi));
            jTextFieldColecao.setText(colecao);
            
            jMenuNovo.setEnabled(true);
            jMenuSalvar.setEnabled(false);
            jMenuEditar.setEnabled(true);
            jMenuExluir.setEnabled(true);
            jMenuCancelar.setEnabled(true);
            jButtonBuscar.setEnabled(false);
            
        }
    }//GEN-LAST:event_jButtonBuscarActionPerformed

    private void jButtonPesquisarColecaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPesquisarColecaoActionPerformed
        FrmConsultaColecao frmContulta = new FrmConsultaColecao(null, true);
        frmContulta.setVisible(true);
        String nomeColecao = frmContulta.getNomeColecao();
        jTextFieldColecao.setText(nomeColecao);
    }//GEN-LAST:event_jButtonPesquisarColecaoActionPerformed

    public void buscarUltimaInsercao(){
        String numEdicao = jTextFieldNumeroEdicao.getText().toString();
        //conecta.desconecta();
        conecta.conexao(); 
        conecta.executaSQL("SELECT max(id_tblRevistas) as numeroPego FROM tblRevistas where numeroEdicao_tblRevistas = '"+numEdicao+"'");
        try { 
            while(conecta.rs.next()){
                String idPego = conecta.rs.getString("numeroPego");
                System.out.println(idPego);
                jTextFieldCodigo.setText(idPego);
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Erro ao buscar id da coleção!\nERRO:"+ex);
        }
    }
    
    public void preencherComboboxCaixa(){
        
        conecta.conexao();
        conecta.executaSQL("select * from tblCaixa order by numero_tblCaixa");
               try{
            conecta.rs.next();
            jTextFieldCaixa.removeAllItems();
            
            do{
                jTextFieldCaixa.addItem(conecta.rs.getString("numero_tblCaixa"));
                
                
            }while(conecta.rs.next());
        }catch (SQLException ex){
            JOptionPane.showMessageDialog(rootPane, "Erro ao preencher combobox!\nERRO:" + ex);
        }
    }
    
    
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBuscar;
    private javax.swing.JButton jButtonPesquisarColecao;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuCancelar;
    private javax.swing.JMenu jMenuEditar;
    private javax.swing.JMenu jMenuExluir;
    private javax.swing.JMenu jMenuNovo;
    private javax.swing.JMenu jMenuSalvar;
    private javax.swing.JTextField jTextFieldAno;
    private javax.swing.JComboBox<String> jTextFieldCaixa;
    private javax.swing.JTextField jTextFieldCodigo;
    private javax.swing.JTextField jTextFieldColecao;
    private javax.swing.JTextField jTextFieldNumeroEdicao;
    // End of variables declaration//GEN-END:variables
}
